"""On-demand fetch of built-in dataset source files.

email-eu-core (SNAP, BSD) and MovieLens (GroupLens, CC BY 4.0) are too large /
externally-owned to commit, so they are fetched from their official host the
first time the dataset is loaded, then cached in `graph_storage/builtin_data/`.
The four other built-ins are generated by NetworkX in-process and need nothing.

`ensure_dataset_files(name)` is called by the loaders in `schema.py` before they
read from disk. It is idempotent: present files are left alone, only missing ones
are downloaded. Raises `FileNotFoundError` (the same error the loaders already
handle as a 503) if a download fails, so a flaky network degrades to "this
built-in is unavailable" rather than a 500.
"""
import io
import os
import shutil
import urllib.error
import urllib.request
import zipfile

DATA_DIR = os.path.join(os.path.dirname(__file__), "graph_storage", "builtin_data")

# Official hosts. SNAP ships two .gz files directly; MovieLens ships one zip we
# extract two members from. Local names match what the schema.py loaders read.
_SNAP_BASE = "https://snap.stanford.edu/data"
_MOVIELENS_ZIP = "https://files.grouplens.org/datasets/movielens/ml-latest-small.zip"

_HTTP_TIMEOUT = 60  # seconds; these are small files (largest ~1 MB compressed)


def _local(*parts):
    return os.path.join(DATA_DIR, *parts)


def _download_to(url, dest_path):
    """Stream `url` into `dest_path`. Atomic via a .part rename so a half-written
    file is never left where a loader would read it."""
    tmp = dest_path + ".part"
    try:
        with urllib.request.urlopen(url, timeout=_HTTP_TIMEOUT) as resp, open(tmp, "wb") as out:
            shutil.copyfileobj(resp, out)
        os.replace(tmp, dest_path)
    except (urllib.error.URLError, OSError) as e:
        if os.path.exists(tmp):
            os.remove(tmp)
        raise FileNotFoundError(f"could not download {url}: {e}")


def _ensure_email_eu_core():
    """Two .gz files, downloaded directly from SNAP under their canonical names
    (the loader reads `email-eu-core.txt.gz` / `email-eu-core-dept.txt.gz`)."""
    targets = {
        "email-eu-core.txt.gz": f"{_SNAP_BASE}/email-Eu-core.txt.gz",
        "email-eu-core-dept.txt.gz": f"{_SNAP_BASE}/email-Eu-core-department-labels.txt.gz",
    }
    for local_name, url in targets.items():
        dest = _local(local_name)
        if not os.path.exists(dest):
            _download_to(url, dest)


def _ensure_movielens_small():
    """One zip from GroupLens; extract ratings.csv / movies.csv and store them
    under the names the loader reads (`ml-ratings.csv` / `ml-movies.csv`)."""
    wanted = {
        "ratings.csv": "ml-ratings.csv",
        "movies.csv": "ml-movies.csv",
    }
    if all(os.path.exists(_local(dest)) for dest in wanted.values()):
        return
    try:
        with urllib.request.urlopen(_MOVIELENS_ZIP, timeout=_HTTP_TIMEOUT) as resp:
            blob = resp.read()
    except (urllib.error.URLError, OSError) as e:
        raise FileNotFoundError(f"could not download {_MOVIELENS_ZIP}: {e}")

    try:
        with zipfile.ZipFile(io.BytesIO(blob)) as zf:
            # Members are nested under `ml-latest-small/`; match by basename.
            members = {os.path.basename(n): n for n in zf.namelist()}
            for src_name, dest_name in wanted.items():
                if src_name not in members:
                    raise FileNotFoundError(f"{src_name} missing from MovieLens zip")
                with zf.open(members[src_name]) as src, open(_local(dest_name), "wb") as out:
                    shutil.copyfileobj(src, out)
    except zipfile.BadZipFile as e:
        raise FileNotFoundError(f"MovieLens zip is corrupt: {e}")


# name → fetcher. Built-ins absent here (karate, …) are generated by NetworkX.
_FETCHERS = {
    "email_eu_core": _ensure_email_eu_core,
    "movielens_small": _ensure_movielens_small,
}


def ensure_dataset_files(name: str) -> None:
    """Download `name`'s source files into builtin_data/ if missing. No-op for
    NetworkX-generated built-ins. Raises FileNotFoundError on download failure."""
    os.makedirs(DATA_DIR, exist_ok=True)
    fetcher = _FETCHERS.get(name)
    if fetcher is not None:
        fetcher()
